# Workflow to build a PEP-517 compatible python project to PyPI
# (and/or Test PyPI).
#
# Currently, this workflow assume the project is versioned using
# setuptools_scm.
#
name: Publish to PyPI

on:
  workflow_call:
    secrets:
      PYPI_API_TOKEN:
        description: API token for publishing to PyPI
        required: false
      TEST_PYPI_API_TOKEN:
        description: API token for publishing to Test PyPI
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Ensure we have a tag
      if: github.ref_type != 'tag' && false
      run: echo "::error title=No Tag::This workflow should only be used on tag refs" && exit 78

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools_scm

    - name: "Paranoia: Check tag"
      run: |
        version=$(python -m setuptools_scm)
        if [ "$version" != "$(python -m setuptools_scm --strip-dev)" ]; then
          echo "::error title=Missing Tag::Version ($version) does not appear to be properly tagged for setuptools_scm"
          exit 78
        else
          echo "::notice title=Version::Version from tag: $version"
        fi

    - name: Build package
      run: python -m build

    - name: Publish to Test PyPI
      # Secrets can not be used in the if: expression directly
      # https://github.com/actions/runner/issues/520
      # https://github.com/actions/runner/issues/1138
      if: env.has-token
      env:
        has-token: ${{ secrets.TEST_PYPI_API_TOKEN != '' }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: env.has-token
      env:
        has-token: ${{ secrets.PYPI_API_TOKEN != '' }}
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
